
name: Run Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs_on: ubuntu-latest

    steps:
      - name: Setup Actions for our repository
        uses: actions/checkout@v4.2.2

      - name: Set up Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: latest

      - name: Install Dependencies
        run: npm Install
      
      - name: Rune Tests
        run: npm test

      

      